const AFFILIATE_APPROVAL_STATUS = {
  PENDING_REVIEW: 'pending_review',
  ON_HOLD: 'on_hold',
  INTERVIEW_SCHEDULED: 'interview_scheduled',
  APPROVED: 'approved',
  REJECTED: 'rejected',
};

const AFFILIATE_APPROVAL_VALUES = Object.values(AFFILIATE_APPROVAL_STATUS);

const AFFILIATE_PENDING_STATUSES = [
  AFFILIATE_APPROVAL_STATUS.PENDING_REVIEW,
  AFFILIATE_APPROVAL_STATUS.ON_HOLD,
  AFFILIATE_APPROVAL_STATUS.INTERVIEW_SCHEDULED,
];

const AFFILIATE_APPROVAL_LABELS = {
  [AFFILIATE_APPROVAL_STATUS.PENDING_REVIEW]: 'Pending review',
  [AFFILIATE_APPROVAL_STATUS.ON_HOLD]: 'On hold',
  [AFFILIATE_APPROVAL_STATUS.INTERVIEW_SCHEDULED]: 'Interview scheduled',
  [AFFILIATE_APPROVAL_STATUS.APPROVED]: 'Approved',
  [AFFILIATE_APPROVAL_STATUS.REJECTED]: 'Rejected',
};

function isAffiliatePending(status) {
  return AFFILIATE_PENDING_STATUSES.includes(status);
}

function isAffiliateApproved(status) {
  return status === AFFILIATE_APPROVAL_STATUS.APPROVED || !status;
}

module.exports = {
  AFFILIATE_APPROVAL_STATUS,
  AFFILIATE_APPROVAL_VALUES,
  AFFILIATE_PENDING_STATUSES,
  AFFILIATE_APPROVAL_LABELS,
  isAffiliatePending,
  isAffiliateApproved,
};
