const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER: 500,
  SERVICE_UNAVAILABLE: 503,
};

const COOKIE_NAMES = {
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
};

const TENANT_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  SUSPENDED: 'suspended',
  PENDING: 'pending',
};

const LOYALTY_STAMP_MODES = {
  BILL: 'bill',
  REQUEST: 'request',
};

const LOYALTY_STAMP_MODE_VALUES = Object.values(LOYALTY_STAMP_MODES);

module.exports = {
  HTTP_STATUS,
  COOKIE_NAMES,
  TENANT_STATUS,
  LOYALTY_STAMP_MODES,
  LOYALTY_STAMP_MODE_VALUES,
};
